spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:C:/Users/17991/Desktop/java shared code/java-course-program/data.db
    username: admin
    password: admin
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: com.example.courseprogram.sqlite.SQLiteDialect
    show-sql: true
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 9090
web:
  upload-path: .\file\

#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true